pose_1:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 0.0
    - 1.57079632679

pose_2:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 0.0
    - -1.57079632679
pose_3:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 3.14159265359
    - 0.0
    - 1.57079632679

pose_4:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 3.14159265359
    - 0.0
    - -1.57079632679

pose_5:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - -3.14159265359
    - 0.0

pose_6:
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 3.14159265359
    - 0.0