pose_1:  # laying down
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 1.57079632679
    - 0.0

pose_2:  # laying down opposite
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - -1.57079632679
    - 0.0

pose_3:  # standing facing from robot
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 0.0
    - 0.0

pose_4:  # standing 45 deg
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.7853981633974483
    - 0.0
    - 0.0

pose_5:  # laying on handle
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 0.0
    - 0.0
    - 1.57079632679

pose_6:  # laying 90 deg
  obj_pos:
    - 0.0
    - 0.0
    - 0.1
  obj_orientation:
    - 1.57079632679
    - 1.57079632679
    - 0.0